### ISSUE TITLE
502 from APIs and uwsgi

### ISSUE THREAD

**Issue by jessemenn** [nasa-jpl/launchbox#23] opened 2022-11-07 16:10 UTC
### Dashboard inoperative after load

I ran through the [Getting Started documentation](https://nasa-jpl.github.io/launchbox/setup/), but once the dashboard loads, I get a 502 error in the console from Axios (originating from ~/api/auth/state:1). Did I miss a step somewhere in the documentation? 

MacOS 12.16.1, Docker version 20.10.17-rd, not sure what other info would be helpful.

Everything in the logs seem fine (minio and postgres and redis startup) but uWSGI does keep logging the following (repeatedly):

```
launchbox-app-1    | > LBJob [11/07/22 08:08:12 AM]
launchbox-app-1    | | * [Event]: Running job: LBStats.update()
launchbox-app-1    | *** has_emperor mode detected (fd: 6) ***
launchbox-app-1    | [uWSGI] getting INI configuration from api.ini
launchbox-app-1    | [uWSGI] getting INI configuration from /usr/src/app/uwsgi/files/common.ini
launchbox-app-1    | *** Starting uWSGI 2.0.20-debian (64bit) on [Mon Nov  7 08:08:23 2022] ***
launchbox-app-1    | compiled with version: 11.2.0 on 21 March 2022 11:00:44
launchbox-app-1    | os: Linux-5.15.64-0-virt #1-Alpine SMP Mon, 05 Sep 2022 08:02:49 +0000
launchbox-app-1    | nodename: aa08c5a6ccdb
launchbox-app-1    | machine: x86_64
launchbox-app-1    | clock source: unix
launchbox-app-1    | pcre jit disabled
launchbox-app-1    | detected number of CPU cores: 2
launchbox-app-1    | current working directory: /usr/src/app/uwsgi/vassals
launchbox-app-1    | detected binary path: /usr/bin/uwsgi-core
launchbox-app-1    | chdir() to /usr/src/app/
launchbox-app-1    | your memory page size is 4096 bytes
launchbox-app-1    |  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
launchbox-app-1    | detected max file descriptor number: 1048576
launchbox-app-1    | lock engine: pthread robust mutexes
launchbox-app-1    | thunder lock: disabled (you can enable it with --thunder-lock)
launchbox-app-1    | bind(): Operation not permitted [core/socket.c line 230]
launchbox-app-1    | unlink(): No such file or directory [core/uwsgi.c line 1675]
launchbox-app-1    | Mon Nov  7 08:08:23 2022 - [emperor] curse the uwsgi instance api.ini (pid: 153)
launchbox-app-1    | Mon Nov  7 08:08:23 2022 - [emperor] removed uwsgi instance api.ini
launchbox-app-1    | *** has_emperor mode detected (fd: 6) ***
launchbox-app-1    | [uWSGI] getting INI configuration from connect.ini
launchbox-app-1    | [uWSGI] getting INI configuration from /usr/src/app/uwsgi/files/common.ini
launchbox-app-1    | *** Starting uWSGI 2.0.20-debian (64bit) on [Mon Nov  7 08:08:38 2022] ***
launchbox-app-1    | compiled with version: 11.2.0 on 21 March 2022 11:00:44
launchbox-app-1    | os: Linux-5.15.64-0-virt #1-Alpine SMP Mon, 05 Sep 2022 08:02:49 +0000
launchbox-app-1    | nodename: aa08c5a6ccdb
launchbox-app-1    | machine: x86_64
launchbox-app-1    | clock source: unix
launchbox-app-1    | pcre jit disabled
launchbox-app-1    | detected number of CPU cores: 2
launchbox-app-1    | current working directory: /usr/src/app/uwsgi/vassals
launchbox-app-1    | detected binary path: /usr/bin/uwsgi-core
launchbox-app-1    | chdir() to /usr/src/app/
launchbox-app-1    | your memory page size is 4096 bytes
launchbox-app-1    |  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
launchbox-app-1    | detected max file descriptor number: 1048576
launchbox-app-1    | lock engine: pthread robust mutexes
launchbox-app-1    | thunder lock: disabled (you can enable it with --thunder-lock)
launchbox-app-1    | bind(): Operation not permitted [core/socket.c line 230]
launchbox-app-1    | unlink(): No such file or directory [core/uwsgi.c line 1675]
launchbox-app-1    | Mon Nov  7 08:08:38 2022 - [emperor] curse the uwsgi instance connect.ini (pid: 154)
launchbox-app-1    | Mon Nov  7 08:08:38 2022 - [emperor] removed uwsgi instance connect.ini
launchbox-app-1    | > LBJob [11/07/22 08:09:14 AM]
launchbox-app-1    | | * [Event]: Running job: LBStats.update()
```

**Comment by addisonhardy** [comment] 2022-11-07 18:53
Hey @jessemenn - thanks for reporting this!  It looks like uWSG is unable to start up the two management instances (`api` and `connect`).  I am going to try to reproduce this issue and will follow up here.

**Comment by addisonhardy** [comment] 2022-11-07 21:27
Following up here - I was able to reproduce the issue on my end.  In the `docker-compose.yml` file, we are linking the `container` folder in the repo to `/usr/src/app` within the `app` Docker container.

The failure to `bind()` is a permissions issue, but we are setting permissions carefully within the container.  I was able to recreate the issue by changing the permissions of the linked `container/uwsgi/sockets` folder on the host OS to be unwritable by my host OS user.  Can you verify that the host OS permissions for the `container` folder (and subfolders) allow writing by the host OS user you're using to run the Docker container?

Another approach to verify this is the issue would be to comment out the `volumes` section under `app` in `docker-compose.yml`.

**Comment by jessemenn** [comment] 2022-11-07 22:35
Can confirm that commenting out `volumes` in the `app` section fixed the issue. 

There were two (likely) non-standard setups on my Mac I hadn't considered -- I'm on a Mac managed by my university so I don't actually have admin, I have some "privileges" app that temporarily grants me admin privs, and I'm using Rancher Desktop instead of Docker Desktop. I suspect there may be some elegant networking that Docker Desktop handles automagically that Rancher hasn't yet implemented. Using Docker Desktop on my managed Mac everything worked as expected.

Appreciate the help!

**Comment by Scotchester** [comment] 2022-11-08 14:22
Glad to hear you got it running, Jesse. I'll go ahead and close this, but will think about whether there's a way to mention this potential roadblock in the docs.

**Closed by Scotchester** 2022-11-08 14:22 UTC
